esphome:
  name: test-mcp
  friendly_name: Test Mcp
  

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api


ota:
  - platform: esphome
    password: !secret ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:



spi:
  clk_pin: GPIO14
  mosi_pin: GPIO13


external_components:
  - source:
      type: local
      path: external_components



# MCP41010
mcp41010:
  id: my_pot
  cs_pin: GPIO15


button:
  - platform: template
    name: "Set Pot to 128"
    on_press:
      then:
        - lambda: |-
            id(my_pot).set_value(128);



  - platform: template
    name: "Set Pot to 0"
    on_press:
      then:
        - lambda: |-
            id(my_pot).set_value(0);
